// Category image mapping. Keys are the Croatian labels used in catalog.js.
// Files live in images/c/. Group images act as fallback for unmatched L3 items.
window.BB_GRPIMG = {
  'Hladnjaci i zamrzivači': 'g-hladnjaci.jpg',
  'Perilice i sušilice rublja': 'g-perilice.jpg',
  'Pranje posuđa': 'g-pranje-posuda.jpg',
  'Pećnice': 'g-pecnice.jpg',
  'Ploče za kuhanje i nape': 'g-ploce.jpg',
  'Televizori i dodaci': 'g-televizori.jpg',
  'Projektori i platna': 'g-projektori.jpg',
  'Video uređaji': 'g-video.jpg',
  'Audio oprema': 'g-audio.jpg',
  'Hi-Fi oprema': 'g-hifi.jpg',
  'Prijenosni audio uređaji': 'g-prijenosni-audio.jpg',
  'Kablovi i dodaci': 'g-kablovi.jpg',
  'Računala i monitori': 'g-racunala.jpg',
  'Pisači i potrošni materijal': 'g-pisaci.jpg',
  'Računalna periferija': 'g-periferija.jpg',
  'Računalne komponente': 'g-komponente.jpg',
  'Pohrana podataka': 'g-pohrana.jpg',
  'Mrežna oprema': 'g-mrezna.jpg',
  'Software': 'g-software.jpg',
  'Mobiteli': 'g-mobiteli.jpg',
  'Tableti': 'g-tableti.jpg',
  'Pametni satovi i narukvice': 'g-satovi.jpg',
  'Mobile/tablet pribor': 'g-mobile-pribor.jpg',
  'Fiksni telefoni': 'g-fiksni.jpg',
  'Fotoaparati': 'g-fotoaparati.jpg',
  'Kamere': 'g-kamere.jpg',
  'Usisavači i čistači': 'g-usisavaci.jpg',
  'Aparati za kavu': 'g-kava.jpg',
  'Glačanje i šivanje': 'g-glacanje.jpg',
  'Priprema hrane': 'g-priprema-hrane.jpg',
  'Priprema pića': 'g-priprema-pica.jpg',
  'Pomagala za kuhinjske aparate': 'g-dodaci-kuhinjski.jpg',
  'Njega lica i tijela': 'g-njega-lica.jpg',
  'Njega kose': 'g-njega-kose.jpg',
  'Njega zubi': 'g-njega-zubi.jpg',
  'Zdravlje': 'g-zdravlje.jpg',
  'Masažeri i ostali uređaji za wellness': 'g-masazeri.jpg',
  'Igraće konzole': 'g-konzole.jpg',
  'Igre': 'g-igre.jpg',
  'Gaming pribor': 'g-gaming-pribor.jpg',
  'Gaming oprema': 'g-gaming-oprema.png',
  'Klima uređaji': 'g-klima.jpg',
  'Grijanje': 'g-grijanje.jpg',
  'Uređaji za kvalitetu zraka': 'g-zrak.jpg',
  'Električna vozila': 'g-el-vozila.png',
  'Biciklizam': 'g-biciklizam.jpg',
  'Romobili skateboardi i role': 'g-romobili.jpg',
  'Fitness oprema': 'g-fitness.jpg',
  'Kampiranje': 'g-kampiranje.jpg',
  'Optički uređaji': 'g-opticki.jpg',
  'Sportska oprema': 'g-sportska.jpg',
  'Vodeni sportovi': 'g-vodeni.jpg',
  'Zimski sportovi': 'g-zimski.jpg',
  'Kuhinjska pomagala i dodaci': 'g-kuhinjska-pomagala.jpg',
  'Pomagala za čišćenje i pospremanje': 'g-ciscenje.jpg',
  'Madraci i jastuci': 'g-madraci.jpg',
  'Kade tuševi i umivaonici': 'g-kade.jpg',
  'Ostala dekorativa': 'g-dekorativa.jpg',
  'Zidna dekorativa i satovi': 'g-zidna-dekorativa.jpg',
  'Tekstilni program': 'g-tekstil.jpg',
  'Rasvjeta': 'g-rasvjeta.jpg',
  'Pametan dom i sigurnost': 'g-pametan-dom.jpg',
  'Sezonske dekoracije': 'g-sezonske.jpg',
  'Pribor za čišćenje': 'g-pribor-ciscenje.jpg',
  'Energetska rješenja': 'g-energetska.jpg',
  'Vrtni namještaj': 'g-vrtni-namjestaj.jpg',
  'Spavaća soba': 'g-spavaca.jpg',
  'Dječija soba': 'g-djecija.jpg',
  'Dnevna soba': 'g-dnevna.jpg',
  'Kuhinja': 'g-kuhinja.jpg',
  'Blagovaonica': 'g-blagovaonica.jpg',
  'Kupaonica': 'g-kupaonica.jpg',
  'Ured': 'g-ured.jpg',
  'Hodnik': 'g-hodnik.jpg',
  'Vrata': 'g-vrata.jpg',
  'Dodaci za vrtni namještaj': 'g-dodaci-vrtni-namjestaj.jpg',
  'Roštilji i pribor': 'g-rostilji.jpg',
  'Bazeni i jacuzziji': 'g-bazeni.jpg',
  'Električni alati': 'g-el-alati.jpg',
  'Akumulatorski alati': 'g-aku-alati.jpg',
  'Ručni alati': 'g-rucni-alati.jpg',
  'Mjerni instrumenti': 'g-mjerni.jpg',
  'Vrtni alati': 'g-vrtni-alati.jpg',
  'Dodatci za alate': 'g-dodaci-alate.jpg',
  'Dodatci za vrt': 'g-dodaci-vrt.jpg',
  'Elektro materijal': 'g-elektro.jpg',
  'Kocke': 'plasticne-kocke.jpg',
  'Daljinski upravljane vodene igračke': 'g-rc-vodene.jpg',
  'Avioni vozila i plovila': 'g-avioni.jpg',
  'Ostale igračke': 'g-ostale-igracke.jpg',
  'Autosjedalice i nosiljke': 'g-autosjedalice.jpg',
  'Oprema za hranjenje': 'g-hranjenje.jpg',
  'Njega bebe': 'g-njega-bebe.jpg',
  'Kozmetika za djecu': 'g-kozmetika-djeca.jpg',
  'Ostala dječja oprema': 'g-ostala-djecja.jpg',
  'Uredski aparati i strojevi': 'g-uredski-aparati.jpg',
  'Papirni program': 'g-papirni.jpg',
  'Kancelarijski pribor': 'g-kancelarijski.jpg',
  'Torbe i pernice': 'g-torbe-pernice.jpg',
  'Pribor za pisanje': 'g-pisanje.jpg',
  'Boje': 'g-boje.jpg',
  'Modelarstvo i maketarstvo': 'g-modelarstvo.jpg',
  'Hobi program ostalo': 'g-crtanje.jpg',
  'Auto elektronika': 'g-auto-audio.jpg',
  'Održavanje vozila': 'g-auto-oprema.jpg',
  'Psi': 'g-psi.jpg',
  'Mačke': 'g-macke.jpg',
  'Ptice': 'oprema-za-pticje-kletke.jpg',
  'Akvaristika': 'g-akvaristika.jpg',
  'Konji': 'g-konji.jpg',
  'Klaviri i klavijature': 'g-klaviri.jpg',
  'Udaraljke': 'g-udaraljke.jpg',
  'Oprema za instrumente': 'g-oprema-instrumenti.jpg',
  'Nosači zvuka': 'g-nosaci-zvuka.jpg',
  'Napitci': 'g-kava-super.jpg',
  'Kućne potrepštine': 'cistila-za-dom.jpg',
  'Baterije i žarulje': 'avto-zarnice.jpg',
  'Obnovljeni uređaji': 'g-mobiteli.jpg',
  'Outlet': 'g-hladnjaci.jpg'
};

window.BB_L3IMG = {
  // Bijela tehnika
  'Dodaci za hladnjake': 'dodatki-za-hladilnike.jpg',
  'Dodaci za pranje i sušenje': 'dodatki-za-pranje-in-susenje.jpg',
  'Dodaci za pranje posuđa': 'dodatki-za-pomivanje.jpg',
  'Ploče sa ugradbenom napom': 'plosce-z-vgrajeno-napo.jpg',
  'Nape': 'nape.jpg',
  'Pribor za nape': 'pribor-za-nape.jpg',
  'Dodaci za kuhanje': 'dodatki-za-kuhanje.jpg',
  // TV i audio
  'Kućna kina (soundbarovi)': 'soundbari.jpg',
  'Muzičke linije': 'hisni-kino.jpg',
  'Platna': 'platna.jpg',
  'DVD uređaji': 'dvd.jpg',
  'Blu-ray uređaji': 'blu-ray.jpg',
  'Audio Kablovi': 'avdio-kabli.jpg',
  'Video kablovi': 'video-kabli.jpg',
  'Prijenosni radio i budilice': 'budilke.jpg',
  'Nosači zvučnika': 'stojala-podstavki.jpg',
  // Računala
  'All-in-One računala': 'all-in-one-racunalniki.jpg',
  'Profesionalni ekrani': 'profesionalni-monitorji.jpg',
  'Serveri': 'strezniki.jpg',
  'Stalci za monitore': 'stojala-podstavki.jpg',
  'Toneri': 'tonerji.jpg',
  'Papir': 'papir-potrosni-material.jpg',
  'Tintni inkjet pisači': 'printer.png',
  'Laserski pisači': 'printer.png',
  'Pisači naljepnica': 'tiskalniki-nalepk.jpg',
  'Računalni zvučnici': 'racunalniski-zvocniki.jpg',
  'Laptop punjači': 'polnilci-za-prenosnike.jpg',
  'Računalne kartice': 'racunalniske-kartice.jpg',
  'Ostale računalne komponente': 'ostale-racunalniske-komponente.jpg',
  'HDD/SSD diskovi ugradni': 'hdd.png',
  'HDD/SSD diskovi externi': 'hdd.png',
  'Grafički tableti': 'risalne-tablice.jpg',
  'Routeri': 'routerji.jpg',
  'Pojačivači dometa i AP': 'ojacevalniki-signala.jpg',
  'Bežični adapteri': 'brezzicne-omrezne-kartice.jpg',
  'Switchevi': 'mrezna-stikala.jpg',
  'Mrežne kartice': 'omrezne-kartice.jpg',
  'Mrežni kablovi': 'omrezni-kabli.jpg',
  'Ostala mrežna oprema': 'ostala-omrezna-oprema.jpg',
  'Windows': 'operacijski-sistemi.jpg',
  'Office': 'paketi-pisarniskih-programov.jpg',
  // Mobilni uređaji i foto
  'Setovi za bežične pozive': 'seti-za-prostorocne-klice.jpg',
  'Klasični mobiteli': 'mobile-dodatki.jpg',
  'Punjači': 'polnilniki.jpg',
  'Bežični telefoni': 'brezzicni-telefoni.jpg',
  'Radijske postaje': 'telefoni-stacionarni.jpg',
  'Stativi': 'stativi.jpg',
  'Dodaci za kamere': 'dodatki-za-kamere.jpg',
  'Pametne narukvice': 'fit-zapestnice.jpg',
  'Pametni prsteni': 'prstani.jpg',
  'Ostali dodaci': 'rezervni-deli-mobilni.jpg',
  // Mali kućanski aparati
  'Vrećice za usisavače': 'vrecke-za-sesalnike.jpg',
  'Aparati za espresso kavu': 'kavni-aparati-espresso.jpg',
  'Aparati za kavu na kapsule': 'kava-v-kapsulah.jpg',
  'Aparati za filter kavu': 'mleta-kava.jpg',
  'Aparati za tjesteninu': 'aparati-za-testenine.jpg',
  'Sokovnici': 'aparati-za-sok.jpg',
  'Kuhala za vodu': 'kuhalniki.jpg',
  'Električne tave': 'elektricne-ponve.jpg',
  'Mesoreznice i aparati za...': 'mesoreznice.jpg',
  'Štapni mikseri': 'namizni-mesalniki.jpg',
  'Dodaci za kuhinjske...': 'dodatki-za-kuhinjske-aparate.jpg',
  'Grijači zraka': 'aparati-za-gretje.jpg',
  // Osobna njega
  'Električne četkice za zube': 'elektricne-zobne-scetke.jpg',
  'Dječje četkice za zube': 'otroske-zobne-scetke.jpg',
  'Paste za zube': 'zobne-paste.jpg',
  'Vodice za usta': 'ustne-vodice.jpg',
  'Dodaci za njegu zubi': 'dodatki-za-nego-zob.jpg',
  'Tuševi za zube': 'medzobna-nega.jpg',
  'Maske za lice': 'obrazne-maske.jpg',
  'Uređaji za čišćenje lica': 'ciscenje-obraza.jpg',
  'Uređaji za uljepšavanje': 'naprave-za-kozmetiko.jpg',
  'Dodaci za šišanje': 'dodatki-za-strizenje.jpg',
  'Češljevi četke i pribor za kosu': 'glavniki-krtace.jpg',
  'Osobne vage': 'osebne-tehtnice.jpg',
  'Ostali medicinski uređaji': 'ostali-medicinski-pripomocki.jpg',
  'Deke i jastuci za grijanje': 'grelni-in-hladilni-pripomocki.jpg',
  'Uređaji za zagrijavanje': 'grelniki.jpg',
  'Uređaji za masažu': 'masazne-mize.jpg',
  // Gaming
  'PlayStation 5': 'playstation-5.jpg',
  'PlayStation VR2': 'playstation-vr2.jpg',
  'PlayStation Portal': 'playstation-portal.jpg',
  'Ostale konzole': 'playstation-4.jpg',
  'Igre za PS4': 'igre-za-ps4.jpg',
  'Igre za PC': 'igre-za-ostale-platforme.jpg',
  'Kontroleri PS4': 'igralni-ploscki-ps4.jpg',
  'Dodaci za PS4': 'dodatki-za-ps4.jpg',
  'Dodaci za PC': 'dodatki-za-pc.jpg',
  'Gamepadovi - više platformi': 'vecplatformni-igralni-ploscki.jpg',
  'Gaming stolovi': 'gaming-mize.jpg',
  'Gaming stolice': 'racunalniski-stoli.jpg',
  'Gaming merchandise': 'gaming-dodatki-za-pc.jpg',
  // Klimatizacija i grijanje
  'Zidni klima uređaji': 'stenske-klimatske-naprave.jpg',
  'Mobilni klima uređaji': 'prenosne-klimatske-naprave.jpg',
  'Pribori za klime': 'dodatki-za-klime.jpg',
  'Infracrvene grijalice': 'infra-peci.jpg',
  'IR paneli': 'infra-peci.jpg',
  'Termostati': 'termostatski-ventili.jpg',
  'Grijalice za terasu': 'grelniki.jpg',
  // Sport i vozila
  'Nosači za bicikle': 'stresni-nosilci-kolesa.jpg',
  'Štitnici': 'rolling-sport-dodatki.jpg',
  'Ostala fitness oprema': 'ostale-fitnes-naprave.jpg',
  'Pokretne stepenice i...': 'tekoce-stopnice.jpg',
  'Oprema za Yogu pilates i druge...': 'joga-pilates.jpg',
  'Fitnes pomagala': 'vadbene-gume.jpg',
  'Teleskopi': 'teleskopi.jpg',
  'Sportovi s loptom': 'nogometne-zoge.jpg',
  'Sportovi s reketa': 'igre-z-loparji.jpg',
  'Borilački sportovi': 'borilne-vescine.jpg',
  'Plivački rekviziti': 'plavalni-pripomocki.jpg',
  'Surf daske i dodaci': 'surf-deske.jpg',
  'Sanjkanje i zabava na...': 'sankanje.jpg',
  'Drugi zimski sportovi': 'smucanje.jpg',
  'Električni romobili': 'elektricni-avtomobili.jpg',
  // Dom
  'Posude za odlaganje hrane': 'shranjevanje-hrane.jpg',
  'Pribori za jelo': 'jedilni-pribori.jpg',
  'Kuhinjski noževi': 'nozi.jpg',
  'Organizatori': 'organizatorji.jpg',
  'Koševi i vreće za smeće': 'kosi-vrecke-smeti.jpg',
  'Kutije vreće i košare za...': 'kosi-kosare-perilo.jpg',
  'Košare i stalci za ruble': 'kosi-kosare-perilo.jpg',
  'Metle i lopate': 'lopatice.jpg',
  'Ostala sredstva za čišćenje': 'ostali-cistilni-pripomocki.jpg',
  'Osvježivači zraka': 'disave-za-dom.jpg',
  'Svijeće i mirisi': 'disave-za-dom.jpg',
  'Prekrivači': 'dekorativne-odeje.jpg',
  'Dekorativni pokrivači': 'dekorativne-odeje.jpg',
  'Jastuci za spavanje': 'nadvlozki.jpg',
  'WC školjke bide i poklopci': 'kotlicki-splakovalniki.jpg',
  'Zidni satovi': 'stenske-ure.jpg',
  'Budilice': 'budilke.jpg',
  'Ogledala': 'ogledala.jpg',
  'Okviri za slike': 'plakati-in-slike.jpg',
  'Ostale zidne dekoracije': 'ostala-stenska-dekoracija.jpg',
  'Umjetna stabla cvijeće i biljke ...': 'umetna-drevesa.jpg',
  'Tepisi i staze': 'preproge-in-tekaci.jpg',
  'Otirači': 'predprazniki.jpg',
  'Tepisi za kupaonu': 'kopalniske-preproge.jpg',
  'Posteljine': 'posteljnine.jpg',
  'Plahte': 'rjuhe.jpg',
  'Ručnici': 'kopalne-brisace.jpg',
  'Ostali tekstilni predmeti': 'kuhinjski-tekstil.jpg',
  'Stropna svjetla': 'stropne-luci.jpg',
  'Zidna svjetla': 'stenske-luci.jpg',
  'Stolne lampe': 'namizne-luci.jpg',
  'Prostostojeće Luči': 'prostostojece-luci.jpg',
  'Dječje lampe': 'otroska-svetila.jpg',
  'Solarne svjetiljke': 'solarna-svetila.jpg',
  'Vanjske svjetiljke': 'zunanja-razsvetljava.jpg',
  'Ostale svjetiljke': 'ostala-svetila.jpg',
  'Poštanski sandučići': 'postni-nabiralniki.jpg',
  'Brave': 'kljucavnice.jpg',
  'Pametni prekidači': 'vticnice-in-stikala.jpg',
  'Pametna zvona': 'pametni-zvonci.jpg',
  'Senzori pokreta': 'senzorji-gibanja.jpg',
  'Unutarnji vrtovi i dodaci': 'notranji-vrtovi.jpg',
  'Sredstva za pranje': 'sredstva-za-pranje.jpg',
  'Pribori za čišćenje doma': 'cistila-za-dom.jpg',
  'Pribori za čišćenje bijele...': 'cistila-za-belo-tehniko.jpg',
  'Ostala energetska...': 'ostale-energetske-resitve.jpg',
  // Namještaj
  'Viseće mreže': 'visece-mreze.jpg',
  'Vrtni kauči': 'vrtni-kavci.jpg',
  'Vrtne ljuljačke': 'vrtni-gugalniki.jpg',
  'Ormari/komode': 'omare-komode.jpg',
  'Ormari/ladice': 'omare-komode.jpg',
  'Fotelje': 'fotelji.jpg',
  'Police': 'police.jpg',
  'Police za knjige': 'police.jpg',
  'Police za dnevnu sobu': 'police.jpg',
  'Police za spavaću sobu': 'police.jpg',
  'Stolice za računala': 'racunalniski-stoli.jpg',
  'Zaštite za vanjski namještaj': 'zascite-zunanje-pohistvo.jpg',
  // Vrt i alati
  'Vrtne škare': 'skarje-za-vrt.jpg',
  'Škare za živicu i travu': 'skarje-za-vrt.jpg',
  'Prozračivači travnjaka': 'prezracevalniki-trave.jpg',
  'Električne pile': 'elektricne-zage.jpg',
  'Brusilice - električni alati': 'brusilniki-el.jpg',
  'Brusilice - aku alati': 'brusilniki-aku.jpg',
  'Multifunkcionalni alati - električni...': 'vecfunkcijsko-el.jpg',
  'Multifunkcionalni alati - aku alati': 'vecfunkcijsko-aku.jpg',
  'Odvijači i udarne bušilice - aku...': 'vijacniki-aku.jpg',
  'Odvijači i udarne bušilice -...': 'vijacniki-el.jpg',
  'Ostali akumulatorski...': 'ostalo-aku-orodje.jpg',
  'Ostali električni alati': 'ostalo-el-orodje.jpg',
  'Akumulatori i punjači': 'baterije-polnilci-orodje.jpg',
  'Setovi ručnog alata': 'seti-rocnega-orodja.jpg',
  'Ostali ručni alati': 'ostalo-rocno-orodje.jpg',
  'Kliješta': 'klesce.jpg',
  'Ključevi': 'kljuci.jpg',
  'Čekići': 'kladiva.jpg',
  'Pile i sjekire': 'rocne-zage-sekire.jpg',
  'Odvijači': 'izvijaci.jpg',
  'Spojnice i stege': 'spone-in-primezi.jpg',
  'Ručne blanje': 'oblici.jpg',
  'Noževi': 'nozi.jpg',
  'Toplinski pištolji i fenovi': 'pistole-vroc-zrak.jpg',
  'Prskalice i pištolji za bojanje': 'pistole-za-barvanje.jpg',
  'Lemilice': 'spajkalniki.jpg',
  'Spajalice i klamerice': 'spenjalniki.jpg',
  'Mjerači': 'merilniki.jpg',
  'Metri': 'tracni-metri.jpg',
  'Niveliri laseri i libele': 'laserji-nivelirji.jpg',
  'Ostali mjerni alati': 'ostalo-merilno-orodje.jpg',
  'Kutometri': 'kotomeri.jpg',
  'Ravnala - mjerni alati': 'ravnila.jpg',
  'Organizatori alata': 'organizatorji-orodja.jpg',
  'Oštrice za alate': 'rezila-za-orodje.jpg',
  'Dodaci za brušenje': 'dodatki-za-brusenje.jpg',
  'Dodaci za pile': 'dodatki-za-zage.jpg',
  'Dodaci za bušilice i...': 'dodatki-za-vrtalnike.jpg',
  'Dodaci za bojanje': 'dodatki-za-barvanje.jpg',
  'Ostali pribor': 'ostali-dodatki-za-orodje.jpg',
  'Vrtne kućice': 'vrtne-lope.jpg',
  'Vrtne dekoracije': 'vrtna-dekoracija.jpg',
  'Vrtne cijevi': 'vrtni-vodovod.jpg',
  'Gnojiva i njega biljaka': 'podlage-in-gnojila.jpg',
  'Zamke i repelenti za životinje': 'pasti-odganjalci.jpg',
  'Ostali dodaci za vrtlarstvo': 'ostali-dodatki-vrtnarjenje.jpg',
  'Produžni kabeli': 'elektricni-podaljski.jpg',
  'Utikači': 'vticnice-in-stikala.jpg',
  'Ostala električna oprema i...': 'elektricni-razdelilniki.jpg',
  // Igračke
  'Plastične kocke za slaganje': 'plasticne-kocke.jpg',
  'Roboti': 'roboti.jpg',
  'RC modeli': 'ostale-rc-igrace.jpg',
  'Ostale igračke na daljinsko...': 'rc-avtomobili.jpg',
  'Trkaći automobili i staze': 'avtomobili-steze.jpg',
  'Zrakoplovi i helikopteri': 'avioni-helikopterji.jpg',
  'Rakete i svemirski...': 'rakete.jpg',
  'Igračke - vozila i plovila': 'makete-vozil.jpg',
  'Ostale igračke': 'ostale-igrace.jpg',
  // Oprema za bebe
  'Autosjedalice': 'g-autosjedalice.jpg',
  'Bočice': 'steklenicke.jpg',
  'Slinčeki': 'slincki.jpg',
  'Ostali pribori za hranjenje': 'ostali-pripomocki-hranjenje.jpg',
  'Posude za hranu i termo posude': 'posodice-za-hrano.jpg',
  'Pribori za dojenje': 'sterilizatorji.jpg',
  'Kahlice i kahlice': 'kahlice.jpg',
  'Ostali pribor za njegu djeteta': 'ostali-pripomocki-nego-otroka.jpg',
  'Higijenski proizvodi': 'otroska-kozmetika.jpg',
  'Dude': 'dude-in-grizala.jpg',
  // Škola i ured
  'Uništivači dokumenata': 'unicevalniki-dokumentov.jpg',
  'Ostali uredski uređaji i pribori': 'ostale-pisarniske-naprave.jpg',
  'Naljepnice i folije': 'nalepke-in-folije.jpg',
  'Poklon papir i vrećice': 'darilni-papirji.jpg',
  'Papir - papirni program': 'papir-papirni-program.jpg',
  'Škare i noževi za pisma': 'skarje-in-nozi-za-pisma.jpg',
  'Potrošni materijali za ured': 'pisarniski-potrosni-material.jpg',
  'Oštrači': 'silcki.jpg',
  'Školske torbe i ruksaci': 'otroski-kovcki-nahrbtniki.jpg',
  'Pernice': 'solski-pripomocki.jpg',
  'Penkale': 'kemicni-svincniki.jpg',
  'Bojice': 'svincniki.jpg',
  'Flomasteri': 'flomastri.jpg',
  'Voštane bojice': 'krede.jpg',
  'Boje za tijelo': 'barve-za-telo.jpg',
  'Vodene boje': 'barve-in-razredcila.jpg',
  'Boje i razrjeđivači': 'barve-in-razredcila.jpg',
  'Kreativni setovi': 'ustvarjalni-seti.jpg',
  'Ostali likovni pribor': 'ostali-likovni-pripomocki.jpg',
  // Auto-moto
  'Auto radio': 'g-auto-audio.jpg',
  'Navigacija': 'navigacija-gps.jpg',
  'Startna pomoć': 'polnilci-avto-akumulatorje.jpg',
  'Auto kozmetika': 'avto-preproge.jpg',
  'EV punjači': 'dodatki-polnilne-postaje.jpg',
  'Kablovi za punjenje': 'elektricni-podaljski.jpg',
  // Kućni ljubimci
  'Posipi za mački WC': 'posipi-macja-stranisca.jpg',
  'Kavezi za ptice': 'oprema-za-pticje-kletke.jpg',
  'Kokošinjci': 'kokosnjaki.jpg',
  'Akvarijska oprema': 'akvariji.jpg',
  // Glazba
  'Klaviri i pianina': 'klavirji-in-pianini.jpg',
  'Set bubnjeva': 'seti-bobnov.jpg',
  'Stalci/postolja': 'stojala-podstavki.jpg',
  'Pribori za glazbala': 'pribor-za-glasbila.jpg',
  'Gramofonske ploče': 'ostali-posneti-mediji.jpg',
  // Supermarket
  'Kava': 'kava-v-zrnju.jpg',
  'Čaj': 'instant-kava.jpg',
  'Voda': 'voda.jpg',
  'Sokovi': 'energijski-napitki.jpg',
  'Deterdženti': 'detergenti-za-posodo.jpg',
  'Sredstva za čišćenje': 'cistila-za-dom.jpg',
  'Papirna konfekcija': 'papir-potrosni-material.jpg',
  'Žarulje': 'avto-zarnice.jpg',
  // second pass
  'Čistači prozora': 'cistilci-za-okna.jpg',
  'Optički mediji CD_DVD_BR': 'dodatki-za-opticne-media.jpg',
  'Optički čitači': 'dodatki-za-opticne-media.jpg',
  'Optički pogoni': 'dodatki-za-opticne-media.jpg',
  'Neprekidna napajanja': 'ups-akumulatorji.jpg',
  'USB razdjelnici hub': 'povezovalni-pc-kabli.jpg',
  'Kompleti tipkovnica/miš': 'kompleti-tipkovnice-miske.jpg',
  'IPL uređaji': 'svetlobna-terapija.jpg',
  'Aparati za vakumiranje': 'dodatki-za-varilnike-folij.jpg',
  'Dodaci za vakumirke': 'dodatki-za-varilnike-folij.jpg',
  'Mjerači i dijagnostički...': 'kompleti-za-prvo-pomoc.jpg',
  'Pribor za brijanje i depilaciju': 'kreme.jpg',
  'Uređaji za mušku njegu': 'obrazne-savne.jpg',
  'Manikure/pedikure': 'licila.jpg',
  'Četkice za zube': 'beljenje-zob.jpg',
  'Sredstva za njegu vode': 'akvarijski-preparati.jpg',
  'Oprema za ribnjake': 'akvarijski-preparati.jpg',
  'Električni generatori...': 'vetrni-generatorji.jpg',
  'Energetske stanice': 'vetrni-generatorji.jpg',
  'Inspekcijske kamere': 'lovske-kamere.jpg',
  'Auto kamere': 'lovske-kamere.jpg',
  'Detektori': 'daljinomeri.jpg',
  'Dalekozori': 'daljinomeri.jpg',
  'Trimeri za travu': 'aku-vrtno-orodje.jpg',
  'Dodaci za vrtni alat': 'dodatki-in-ostala-orodja.jpg',
  'Dodaci i drugi alati': 'dodatki-in-ostala-orodja.jpg',
  'Tegle i posude': 'sobne-rastline.jpg',
  'Kompresori za auto': 'dvigalke-za-avto.jpg',
  'Boksevi i ograde za pse': 'transport-malih-zivali.jpg',
  'Pasja oprema za putovanje': 'transport-malih-zivali.jpg',
  'Mačja oprema za putovanje': 'transport-malih-zivali.jpg',
  'Ležišta jastuci i deke za pse': 'nastilji-in-stelje.jpg',
  'Njega pasa': 'nega-malih-zivali.jpg',
  'Njega mačke': 'nega-malih-zivali.jpg',
  'Grebala i mačja stabla': 'igrace-oprema-kletke.jpg',
  'Igračke za mačke': 'igrace-oprema-kletke.jpg',
  'Oprema za vanjske ptice': 'dodatki-za-ptice.jpg',
  'Dječji stolovi': 'risalne-mize.jpg',
  'Kuhinjska kolica': 'vozicki-stolice-lestve.jpg',
  'Tuš kabine': 'kanalete-za-prhe.jpg',
  'Tuševi': 'kanalete-za-prhe.jpg',
  'Umivaonici za kupaonicu': 'kanalete-za-prhe.jpg',
  'Dodaci za prozore': 'nalepke-in-tapete.jpg',
  'Kante i rukavice': 'rokavice.jpg',
  'Dodaci za kupaonicu': 'toaletne-torbe.jpg',
  'Dekorativni dodaci': 'vaze-in-okraski.jpg',
  'Ispravljači': 'rele.jpg',
  'Božićne dekoracije': 'velikonocna-dekoracija.jpg',
  'Sredstva za uklanjanje...': 'odstranjevalci-plesni.jpg',
  'Dodaci za električna...': 'rezervni-deli-skiroji.jpg',
  'Romobili': 'rezervni-deli-skiroji.jpg',
  'Dodaci za bicikle': 'celade-in-plezalniki.jpg',
  'Oprema za bicikle': 'celade-in-plezalniki.jpg',
  'Koturaljke i roleri': 'rezervni-deli-rolerji.jpg',
  'Trake za trčanje': 'tek.jpg',
  'Trampolini i dodaci': 'fitnes-igrace.jpg',
  'Oprema i pribor za kampiranje': 'oprema-pohodnistvo.jpg',
  'Mikroskopi': 'znanstveni-seti.jpg',
  'Drugi sportovi': 'sporti-s-kijem.jpg',
  'Oprema za vodene sportove': 'wing-foili.jpg',
  'Proizvodi na napuhavanje': 'vodni-tobogani.jpg',
  'Dodaci za ljetni program': 'dodatki-poletni-program.jpg',
  'SUP stand up paddleboard': 'wind-surf-deske.jpg',
  'Čamci': 'plovila.jpg',
  'Registratori': 'mape-in-fascikli.jpg',
  'Klamerice': 'spenjaci.jpg',
  'Bušači': 'luknjaci.jpg',
  'Kuverte': 'kuverte-in-ovojnice.jpg',
  'Sveske': 'belezke.jpg',
  'Oprema za crtanje': 'slikarska-stojala.jpg',
  'Blokovi za crtanje': 'risalni-bloki.jpg',
  'Plastelin': 'modelirne-mase.jpg',
  'Tehničke olovke': 'tehnicni-svincniki.jpg',
  'Šestari': 'sestila.jpg',
  'Kaligrafska pera': 'kaligrafska-peresa.jpg',
  // third pass — cat-icons folder (main-line leaves)
  'Hladnjaci': 'i-hladnjaci.webp',
  'Zamrzivači': 'i-zamrzivaci.webp',
  'Vinske vitrine, hladnjaci za vino': 'i-hladnjaci.webp',
  'Perilice rublja': 'i-perilice-rublja.webp',
  'Perilice-sušilice rublja': 'i-perilice-susilice.webp',
  'Sušilice rublja': 'i-susilice-rublja.webp',
  'Perilice posuđa': 'i-perilice-posuda.webp',
  'Sudoperi': 'i-sudoperi.webp',
  'Kuhinjske slavine': 'i-slavine.webp',
  'Pećnice': 'i-pecnice.webp',
  'Mikrovalne pećnice': 'i-mikrovalne.webp',
  'Ugradbene ploče za kuhanje': 'i-ploca.webp',
  'Prijenosne ploče za kuhanje': 'i-prijenosne-ploce.webp',
  'Setovi ploča i pećnica': 'i-setovi-ploca.webp',
  'Štednjaci': 'i-pecnice.webp',
  'Televizori': 'i-tv.webp',
  'Ostali TV dodaci': 'i-tv-dodaci.webp',
  'TV nosači': 'i-tv-nosaci.webp',
  'Antene i oprema': 'i-antene.webp',
  'Daljinski upravljači': 'i-daljinski.webp',
  'Digitalni prijamnici': 'i-prijamnici.webp',
  'Projektori': 'i-projektori.webp',
  'Dodaci za projektore': 'i-dodaci-projektori.webp',
  'Slušalice': 'i-slusalice.webp',
  'Karaoke': 'i-karaoke.webp',
  'Mikrofoni': 'i-mikrofoni.webp',
  'Prijenosni zvučnici i zvuč...': 'i-zvucnici.webp',
  'Audio dodaci': 'i-konektori.webp',
  'Pojačala': 'i-pojacala.webp',
  'CD player': 'i-cd.webp',
  'Radio uređaji': 'i-receiveri.webp',
  'Gramofoni': 'i-gramofoni.webp',
  'Receiveri': 'i-receiveri.webp',
  'Zvučnici Hi-Fi': 'i-hifi-zvucnici.webp',
  'Diktafoni': 'i-diktafoni.webp',
  'MP3 i MP4 Playeri': 'i-mp3.webp',
  'Discmani': 'i-discmani.webp',
  'Konektori': 'i-konektori.webp',
  'Adapteri': 'i-adapteri.webp',
  'Laptopi': 'i-laptopi.webp',
  'Stolna računala': 'i-stolna.webp',
  'Monitori': 'i-monitori.webp',
  'Tableti': 'i-tableti.webp',
  'Čitači knjiga': 'i-citaci-knjiga.webp',
  'Tipkovnice': 'i-tipkovnice.webp',
  'Miševi': 'i-misevi.webp',
  'Podloge za miš': 'i-podloge.webp',
  'Web kamere': 'i-web-kamere.webp',
  'Računalni mikrofoni': 'i-pc-mikrofoni.webp',
  'Čitači kartica': 'i-citaci-kartica.webp',
  'Multimedijski playeri': 'i-multimedijski.webp',
  'Torbe za laptope': 'i-torbe-laptop.webp',
  'Računalni dodaci': 'i-torbe-laptop.webp',
  'Procesori': 'i-procesori.webp',
  'Matične ploče': 'i-maticne.webp',
  'Grafičke kartice': 'i-graficke.webp',
  'Radne memorije RAM': 'i-ram.webp',
  'Kućišta': 'i-kucista.webp',
  'Napajanja': 'i-kucista.webp',
  'Zvučne kartice': 'i-zvucne-kartice.webp',
  'TV kartice': 'i-tv-kartice.webp',
  'Memorijske kartice': 'i-memorijske.webp',
  'USB stickovi': 'i-usb-stick.webp',
  'Tintni inkjet pisači': 'i-printeri.webp',
  '3D pisači': 'i-3d-printeri.webp',
  '3D olovke': 'i-3d-printeri.webp',
  '3D ispis - potrošni materijal': 'i-3d-printeri.webp',
  'Tinte': 'i-printeri.webp',
  'Smartphone': 'i-smartphone.webp',
  'Zapreka': 'i-smartphone.webp',
  'Zaštitne folije i stakla': 'i-zastitna-stakla.webp',
  'Zaštitne maske i torbice': 'i-drzaci.webp',
  'Držači i postolja': 'i-drzaci.webp',
  'Pametni satovi': 'i-satovi.webp',
  'Pametni satovi za djecu': 'i-satovi.webp',
  'Dodaci za satove': 'i-satovi.webp',
  'Mirrorless fotoaparati': 'i-fotoaparati.webp',
  'Kompaktni fotoaparati': 'i-kompaktni.webp',
  'Objektivi': 'i-objektivi.webp',
  'Video kamere': 'i-video-kamere.webp',
  'Ostali foto dodaci': 'i-foto-dodaci.webp',
  'Akcijske kamere': 'i-akcijske.webp',
  'Dronovi': 'i-dronovi.webp',
  'Nintendo konzole': 'i-nintendo.webp',
  'Igre za PS5': 'i-igre-ps5.webp',
  'Igre za Nintendo': 'i-igre-nintendo.webp',
  'Igre za Xbox': 'i-igre-xbox.webp',
  'Kontroleri PS5': 'i-kontroleri.webp',
  'Dodaci za PS5': 'i-ps-dodaci.webp',
  'Dodaci za Nintendo': 'i-nintendo-dodaci.webp',
  'Volani': 'i-volani.webp',
  'VR naočale': 'i-vr.webp',
  'Klasični usisavači': 'i-klasicni-usisavaci.webp',
  'Robotski usisavači': 'i-robotski.webp',
  'Štapni usisavači': 'i-stapni-usisavaci.webp',
  'Vodeni i parni usisavači': 'i-vodeni-usisavaci.webp',
  'Ručni usisavači': 'i-rucni-usisavaci.webp',
  'Parni čistači': 'i-parni-cistaci.webp',
  'Dodaci za usisavače': 'i-dodaci-usisavaci.webp',
  'Aparati za kavu na kapsule': 'i-kapsule.webp',
  'Aparati za filter kavu': 'i-filter-kava.webp',
  'Kuhala za tursku kavu': 'i-turska-kava.webp',
  'Kafeterije': 'i-kafeterije.webp',
  'Pribori za pripremu kave': 'i-mlinci.webp',
  'Glačala': 'i-glacala.webp',
  'Parne postaje': 'i-parne-postaje.webp',
  'Steameri': 'i-steameri.webp',
  'Daske za glačanje': 'i-daske-glacanje.webp',
  'Dodaci za glačanje': 'i-dodaci-glacanje.webp',
  'Šivaći strojevi': 'i-sivaci.webp',
  'Airfryeri i friteze': 'i-airfryeri.webp',
  'Kuhinjski roboti': 'i-kuhinjski-roboti.webp',
  'Multipraktici': 'i-kuhinjski-roboti.webp',
  'Pekači kruha': 'i-pekaci-kruha.webp',
  'Tosteri i grill tosteri': 'i-tosteri.webp',
  'Aparati za sladoled': 'i-sladoled.webp',
  'Aparati za vafle': 'i-vafle.webp',
  'Parna kuhala': 'i-parna-kuhala.webp',
  'Peći za pizze': 'i-pizza.webp',
  'Dehidratori': 'i-dehidratori.webp',
  'Kuhinjske vage': 'i-vage.webp',
  'Ručni mikseri': 'i-mikseri.webp',
  'Citrusete': 'i-sokovnici.webp',
  'Blenderi': 'i-blenderi.webp',
  'Filtratori za vodu': 'i-filtratori.webp',
  'Ledomati': 'i-ledomati.webp',
  'Aparati za brijanje': 'i-brijaci.webp',
  'Epilatori i depilatori': 'i-epilatori.webp',
  'Sušila za kosu': 'i-susila-kose.webp',
  'Pegle za kosu': 'i-cetke-kosa.webp',
  'Četke za oblikovanje kose': 'i-cetke-kosa.webp',
  'Vikleri': 'i-vikleri.webp',
  'Aparati za šišanje': 'i-sisanje.webp',
  'Ventilatori': 'i-ventilatori.webp',
  'Pročišćivači zraka': 'i-procistaci.webp',
  'Odvlaživači zraka': 'i-odvlazivaci.webp',
  'Ovlaživači zraka': 'i-ovlazivaci.webp',
  'Dodaci za aparate za...': 'i-ovlazivaci.webp',
  'Bojleri': 'i-grijalice.webp',
  'Konvektori': 'i-konvektori.webp',
  'Zidne grijalice': 'i-zidne-grijalice.webp',
  'Kaloriferi': 'i-kaloriferi.webp',
  'Električni radijatori': 'i-radijatori.webp',
  'Kamini i peći na drva': 'i-kamini.webp',
  'Električni dvostruki bicikli': 'i-el-rolke.webp',
  'Električni bicikli': 'i-el-bicikli.webp',
  'Planinski bicikli': 'i-planinski-bicikli.webp',
  'Skateboards': 'i-skateboard.webp',
  'Utezi i stalci': 'i-utezi.webp',
  'Eliptični trenažeri Orbitrek': 'i-elipticni.webp',
  'Sobni bicikli': 'i-sobni-bicikli.webp',
  'Veslački simulatori': 'i-veslacki.webp',
  'Fitness stanice i klupe': 'i-fitness-stanice.webp',
  'Šatori i tuneli': 'i-kampiranje.webp',
  'Namještaj za kampiranje': 'i-kampiranje.webp',
  'Rashladne torbe': 'i-rashladne-torbe.webp',
  'Oprema za spavanje': 'i-kampiranje.webp',
  'Vremenske stanice': 'i-vremenske.webp',
  'Pametne kamere': 'i-pametne-kamere.webp',
  'Pametni asistenti': 'i-asistenti.webp',
  'Zvona i interfoni': 'i-domofon.webp',
  'Sefovi': 'i-okovi.webp',
  'Mjerači kvalitete zraka': 'i-vremenske.webp',
  'Pametna rasvjeta': 'i-pametna-rasvjeta.webp',
  'Ručne svjetiljke': 'i-rucne-svjetiljke.webp',
  'Dekorativne svjetiljke': 'i-dekorativne-svjetiljke.webp',
  'Žarulje i rasvjetni elementi': 'i-pametna-rasvjeta.webp',
  'Baterije akumulatori i...': 'i-ups.webp',
  'Solarni pogoni i paneli': 'i-solarni.webp',
  'Kalkulatori': 'i-kalkulatori.webp',
  'Plastifikatori': 'i-kalkulatori.webp',
  'Giljotine i rezači': 'i-kalkulatori.webp',
  'Auto radio': 'i-auto-radio.webp',
  'Navigacija': 'i-navigacija.webp',
  'Usisavači za auto': 'i-rucni-usisavaci.webp',
  'Kompresori za auto': 'i-kompresori.webp',
  'Zidne stanice': 'i-energetske-stanice.webp',
  'Hrana za pse': 'i-hrana-psi.webp',
  'Hrana za mačke': 'i-hrana-macke.webp',
  'Mačji WC-i': 'i-macji-wc.webp',
  'Dodaci za mački WC': 'i-dodaci-macji-wc.webp',
  'Grebala i mačja stabla': 'i-grebala.webp',
  'Igračke za mačke': 'i-igracke-macke.webp',
  'Njega mačke': 'i-njega-macke.webp',
  'Njega pasa': 'i-njega-psa.webp',
  'Ležišta jastuci i deke za pse': 'i-lezista-psi.webp',
  'Ogrlice povodci i ogrlice': 'i-povodci.webp',
  'Ostala oprema za pse': 'i-ostala-oprema-psi.webp',
  'Pasja oprema za putovanje': 'i-putovanje-psi.webp',
  'Mačja oprema za putovanje': 'i-putovanje-macke.webp',
  'Boksevi i ograde za pse': 'i-ostala-oprema-psi.webp',
  'Kavezi za ptice': 'i-kavezi-ptice.webp',
  'Oprema za vanjske ptice': 'i-vanjske-ptice.webp',
  'Akvarijska oprema': 'i-akvarijska.webp',
  'Oprema za ribnjake': 'i-ribnjaci.webp',
  'Njega dlake za konje': 'i-konji.webp',
  'Vrtne stolice': 'i-vrtne-stolice.webp',
  'Vrtne stolovi': 'i-vrtni-stolovi.webp',
  'Setovi vrtnog namještaja': 'i-vrtni-setovi.webp',
  'Ležaljke': 'i-lezaljke.webp',
  'Vrtni ormarići': 'i-vrtni-ormarici.webp',
  'Ostali vrtni namještaj i...': 'i-vrtni-setovi.webp',
  'Viseće mreže': 'i-visece-mreze.webp',
  'Vanjski podovi': 'i-vanjski-podovi.webp',
  'Garderobni ormari - spavać...': 'i-garderobni-spavaca.webp',
  'Noćni ormarići': 'i-nocni-ormarici.webp',
  'Police za spavaću sobu': 'i-police-spavaca.webp',
  'Dječji stolovi': 'i-djecji-stolovi.webp',
  'Dječji ormarići i ladice': 'i-djecji-ormarici.webp',
  'Dječje stolice': 'i-djecje-stolice.webp',
  'Garniture za sjedenje': 'i-garniture.webp',
  'Podnožja i taburei': 'i-taburei.webp',
  'Klupske pomoćne stolice': 'i-klupske-stolice.webp',
  'Police za dnevnu sobu': 'i-police-dnevna.webp',
  'Police za knjige': 'i-police-knjige.webp',
  'Namještaj za pohranu i...': 'i-namjestaj-pohrana.webp',
  'Organizatori za ormariće': 'i-organizatori-ormarici.webp',
  'Kuhinjski ormari': 'i-kuhinjski-ormari.webp',
  'Zidna rješenja za pohranu': 'i-zidna-pohrana.webp',
  'Kuhinjski otoci': 'i-kuhinjski-otoci.webp',
  'Kuhinjska kolica': 'i-kuhinjska-kolica.webp',
  'Blagovaonske stolice': 'i-blagovaonske-stolice.webp',
  'Blagovaonski stolovi': 'i-blagovaonski-stolovi.webp',
  'Blagovaonske garniture': 'i-garniture.webp',
  'Barske stolice': 'i-barske-stolice.webp',
  'Barski stolovi': 'i-barski-stolovi.webp',
  'Barske garniture': 'i-barske-garniture.webp',
  'Kredenci': 'i-kredenci.webp',
  'Kupaonski ormarići': 'i-kupaonski-ormarici.webp',
  'Umivaonici za kupaonicu': 'i-umivaonici.webp',
  'Tuš kabine': 'i-tus-kabine.webp',
  'Tuševi': 'i-tusevi.webp',
  'Zavjese i dodaci za tuš kabine': 'i-tus-zavjese.webp',
  'WC školjke bide i poklopci': 'i-wc.webp',
  'Kupaonske armature': 'i-slavine.webp',
  'Ormarići za obuću': 'i-ormarici-obuca.webp',
  'Garderobni ormari - hodnik': 'i-predsoba.webp',
  'Stalci za odjeću': 'i-stalci-odjeca.webp',
  'Kuke vješalice': 'i-kuke.webp',
  'Dodaci za prozore': 'i-dodaci-prozori.webp',
  'Garažna vrata': 'i-garazna-vrata.webp',
  'Okovi': 'i-okovi.webp',
  'Madraci': 'i-madraci.webp',
  'Jastuci za spavanje': 'i-jastuci-spavanje.webp',
  'Pokrivači': 'i-pokrivaci.webp',
  'Navlake za jastuke': 'i-navlake.webp',
  'Posteljine': 'i-posteljine.webp',
  'Zavjese': 'i-zavjese.webp',
  'Jastuci': 'i-jastuci.webp',
  'Čaše i šalice': 'i-case.webp',
  'Kuhinjski noževi': 'i-nozevi.webp',
  'Bar oprema': 'i-bar.webp',
  'Posuđe za pečenje': 'i-pecenje.webp',
  'Posuđe za kuhanje': 'i-posude-kuhanje.webp',
  'Tanjuri zdjele i posude za...': 'i-posude-kuhanje.webp',
  'Dodaci i pomagala za...': 'i-posude-kuhanje.webp',
  'Deterdženti': 'i-deterdzenti.webp',
  'Četke metle krpe i sušve': 'i-cetke-metle.webp',
  'Kante i rukavice': 'i-kante.webp',
  'Svijeće i mirisi': 'i-svijece.webp',
  'Ručnici': 'i-rucnici.webp',
  'Visokotlačni čistači': 'i-visokotlacni.webp',
  'Lančane pile': 'i-lancane-pile.webp',
  'Vrtne škare': 'i-vrtne-skare.webp',
  'Škare za živicu i travu': 'i-vrtne-skare.webp',
  'Ostali vrtni alati': 'i-ostali-vrtni.webp',
  'Ručni vrtni alati': 'i-ostali-vrtni.webp',
  'Dodaci za vrtni alat': 'i-dodaci-vrtni-alat.webp',
  'Puhač/usisavač': 'i-puhac.webp',
  'Kosilice': 'i-ostali-vrtni.webp',
  'Komposteri': 'i-komposteri.webp',
  'Staklenici': 'i-staklenici.webp',
  'Zaštitna mreža': 'i-zastitna-mreza.webp',
  'Vodene crpke': 'i-vodene-crpke.webp',
  'Ograda': 'i-zastitna-mreza.webp',
  'Vrtne kućice': 'i-vrtne-kucice.webp',
  'Kompresori': 'i-kompresori.webp',
  'Aparati za varenje': 'i-varenje.webp',
  'Pribor za varenje': 'i-pribor-varenje.webp',
  'Glodalice': 'i-glodalice.webp',
  'Blanjalice': 'i-blanjalice.webp',
  'Bazeni': 'i-bazeni.webp',
  'Oprema i pribor za bazene': 'i-bazeni.webp',
  'Pribor za roštilje': 'i-pribor-rostilj.webp',
  'Ugljen za roštilj': 'i-ugljen.webp',
  'Roštilji na drveni ugljen': 'i-rostilj-ugljen.webp',
  'Električni roštilji': 'i-rostilj-ugljen.webp',
  'Plinski roštilji': 'i-rostilj-ugljen.webp',
  'Vrtni roštilji posebni roštilji': 'i-rostilj-ugljen.webp',
  'Peći za pizzu - Roštilji i pribor': 'i-pizza.webp',
  'Produžni kabeli': 'i-produzni.webp',
  'Utikači': 'i-utikaci.webp',
  'Školske torbe i ruksaci': 'i-skolske.webp',
  'Vodene boje': 'i-vodene-boje.webp',
  'Voštane bojice': 'i-vostane.webp',
  'Četkice za zube': 'i-cetkice-zube.webp',
  'Tuševi za zube': 'i-tusevi-zube.webp',
  'Mjerači i dijagnostički...': 'i-tlakomjeri.webp',
  'Ostali medicinski uređaji': 'i-medicinski.webp',
  'Deke i jastuci za grijanje': 'i-grelne-deke.webp',
  'Uređaji za masažu': 'i-masazeri.webp',
  'Uređaji za mušku njegu': 'i-muska-njega.webp',
  'Pribor za brijanje i depilaciju': 'i-dodaci-brijanje.webp',
  'Manikure/pedikure': 'i-manikura.webp',
  'IPL uređaji': 'i-ipl.webp',
  'Kuhala za vodu': 'i-kuhala-vode.webp',
  'Sokovnici': 'i-sokovnici.webp',
  'Štapni mikseri': 'i-mikseri.webp',
  'Aparati za vakumiranje': 'i-vakumiranje.webp',
  'Klima uređaji': 'i-klima.webp',
  'Zidni klima uređaji': 'i-klima.webp',
  'Grijači zraka': 'i-grijalice.webp',
  'Grijalice za terasu': 'i-terasa-grijalice.webp',
  'Infracrvene grijalice': 'i-ir-paneli.webp',
  'IR paneli': 'i-ir-paneli.webp',
  'Termostati': 'i-termostati.webp',
  'Nape': 'i-nape.webp',
  'Električni romobili': 'i-el-romobili.webp',
  'Dodaci za električna...': 'i-oprema-el.webp',
  'Oprema za bicikle': 'i-bicikl-oprema.webp',
  'Dodaci za bicikle': 'i-bicikl-oprema.webp',
  'Romobili': 'i-romobili.webp',
  'Koturaljke i roleri': 'i-roleri.webp',
  'Štitnici': 'i-stitnici.webp',
  'Fitnes pomagala': 'i-fitnes-pomagala.webp',
  'Trampolini i dodaci': 'i-trampolini.webp',
  'Dalekozori': 'i-dalekozori.webp',
  'Borilački sportovi': 'i-borilacki.webp',
  'Sportovi s loptom': 'i-lopta.webp',
  'Sportovi s reketa': 'i-reketi.webp',
  'Drugi sportovi': 'i-drugi-sportovi.webp',
  'Čamci': 'i-camci.webp',
  'Proizvodi na napuhavanje': 'i-napuhavanje.webp',
  'Zidni satovi': 'i-zidni-satovi.webp',
  'Budilice': 'i-budilice.webp',
  'Božićne dekoracije': 'i-bozic.webp',
  'Energetske stanice': 'i-energetske-stanice.webp',
  'Neprekidna napajanja': 'i-ups.webp',
  'USB razdjelnici hub': 'i-usb-hub.webp',
  'Routeri': 'i-routeri.webp',
  'Windows': 'i-software.webp',
  'Laserski pisači': 'i-printeri.webp',
  'Prijenosni pisači': 'i-printeri.webp',
  'Grafički tableti': 'i-graficki-tableti.webp',
  'Klasični mobiteli': 'i-klasicni-mobiteli.webp',
  'Bežični telefoni': 'i-fiksni.webp',
  'Radijske postaje': 'i-radijske.webp',
  'Pametni prsteni': 'i-prsten.webp',
  'Igre za PC': 'i-igre-pc.webp',
  'Gaming stolice': 'i-gaming-stolice.webp',
  'Gaming merchandise': 'i-gaming-merch.webp',
  'Čistači prozora': 'i-cistaci-prozora.webp',
  'HDD/SSD diskovi ugradni': 'i-vgradni-diski.webp',
  'HDD/SSD diskovi externi': 'i-vanjski-diski.webp',
  'Hladnjaci ': 'i-hladnjaci-pc.webp',
  'Optički pogoni': 'i-opticki-pogoni.webp',
  'Optički čitači': 'i-opticki-citaci.webp',
  'Računalni zvučnici': 'i-pc-zvucnici.webp'
};
